"""i

Revision ID: fbaf29a637a9
Revises: 
Create Date: 2023-11-27 11:20:35.817631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbaf29a637a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bauteilart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bauteilart', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='heat'
    )
    op.create_table('bauteilkategorie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bauteilkategorie', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='heat'
    )
    op.create_table('change_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='heat'
    )
    op.create_table('heat_sanr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heat_sanr', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('reman_heat_sanr', sa.String(length=255), nullable=True),
    sa.Column('as_heat_sanr', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='heat'
    )
    op.create_table('naels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nael_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='heat'
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='heat'
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('username'),
    schema='heat'
    )
    op.create_table('wits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='heat'
    )
    op.create_table('roles_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['heat.role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['heat.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='heat'
    )
    op.create_table('teile_sanr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teil_sanr', sa.String(length=255), nullable=True),
    sa.Column('change_index', sa.String(length=20), nullable=True),
    sa.Column('bauteil_art', sa.String(length=255), nullable=True),
    sa.Column('bauteil_kategorie', sa.String(length=255), nullable=True),
    sa.Column('part_start_date', sa.Date(), nullable=True),
    sa.Column('heat_start_date', sa.Date(), nullable=True),
    sa.Column('part_end_date', sa.Date(), nullable=True),
    sa.Column('heat_end_date', sa.Date(), nullable=True),
    sa.Column('bauteilkategorie_id', sa.Integer(), nullable=True),
    sa.Column('bauteilart_id', sa.Integer(), nullable=True),
    sa.Column('wit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bauteilart_id'], ['heat.bauteilart.id'], ),
    sa.ForeignKeyConstraint(['bauteilkategorie_id'], ['heat.bauteilkategorie.id'], ),
    sa.ForeignKeyConstraint(['wit_id'], ['heat.wits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teil_sanr'),
    schema='heat'
    )
    op.create_table('vgs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vg_nr', sa.String(length=255), nullable=True),
    sa.Column('heat_id', sa.Integer(), nullable=True),
    sa.Column('einsatz_datum', sa.Date(), nullable=True),
    sa.Column('auslauf_datum', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['heat_id'], ['heat.heat_sanr.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='heat'
    )
    op.create_table('change_mgmt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heat_sanr', sa.Integer(), nullable=True),
    sa.Column('bewertung', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('nael_id', sa.Integer(), nullable=True),
    sa.Column('teil_sanr_vor', sa.Integer(), nullable=True),
    sa.Column('teil_sanr_danach', sa.Integer(), nullable=True),
    sa.Column('impact', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['heat.change_group.id'], ),
    sa.ForeignKeyConstraint(['heat_sanr'], ['heat.heat_sanr.id'], ),
    sa.ForeignKeyConstraint(['nael_id'], ['heat.naels.id'], ),
    sa.ForeignKeyConstraint(['teil_sanr_danach'], ['heat.teile_sanr.id'], ),
    sa.ForeignKeyConstraint(['teil_sanr_vor'], ['heat.teile_sanr.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='heat'
    )
    op.create_table('heat_bom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heat_sanr', sa.Integer(), nullable=True),
    sa.Column('bom_id', sa.String(length=255), nullable=True),
    sa.Column('einsatz_datum', sa.Date(), nullable=True),
    sa.Column('auslauf_datum', sa.Date(), nullable=True),
    sa.Column('teile_sanr_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['heat_sanr'], ['heat.heat_sanr.id'], ),
    sa.ForeignKeyConstraint(['teile_sanr_id'], ['heat.teile_sanr.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='heat'
    )
    op.create_table('teile_sanr_vor_nach',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nael_id', sa.Integer(), nullable=True),
    sa.Column('teil_sanr_vor', sa.Integer(), nullable=True),
    sa.Column('teil_sanr_danach', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nael_id'], ['heat.naels.id'], ),
    sa.ForeignKeyConstraint(['teil_sanr_danach'], ['heat.teile_sanr.id'], ),
    sa.ForeignKeyConstraint(['teil_sanr_vor'], ['heat.teile_sanr.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='heat'
    )
    op.create_table('vg_boms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wit_id', sa.Integer(), nullable=True),
    sa.Column('vg_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vg_id'], ['heat.vgs.id'], ),
    sa.ForeignKeyConstraint(['wit_id'], ['heat.wits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='heat'
    )
    with op.batch_alter_table('roles_users', schema='heat') as batch_op:
        batch_op.drop_constraint('roles_users_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('roles_users_role_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'role', ['role_id'], ['id'], referent_schema='heat')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], referent_schema='heat')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles_users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('roles_users_role_id_fkey', 'role', ['role_id'], ['id'])
        batch_op.create_foreign_key('roles_users_user_id_fkey', 'user', ['user_id'], ['id'])
        
    op.drop_table('vg_boms', schema='heat')
    op.drop_table('teile_sanr_vor_nach', schema='heat')
    op.drop_table('heat_bom', schema='heat')
    op.drop_table('change_mgmt', schema='heat')
    op.drop_table('vgs', schema='heat')
    op.drop_table('teile_sanr', schema='heat')
    op.drop_table('roles_users', schema='heat')
    op.drop_table('wits', schema='heat')
    op.drop_table('user', schema='heat')
    op.drop_table('role', schema='heat')
    op.drop_table('naels', schema='heat')
    op.drop_table('heat_sanr', schema='heat')
    op.drop_table('change_group', schema='heat')
    op.drop_table('bauteilkategorie', schema='heat')
    op.drop_table('bauteilart', schema='heat')
    # ### end Alembic commands ###
